# Generated by Django 5.0.7 on 2024-10-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauthgoogle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_info',
            new_name='UserInfo',
        ),
    ]
