# Generated by Django 5.0.7 on 2024-07-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('messaggio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nome_luogo', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=100)),
                ('citta', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=5)),
                ('descrizione', models.TextField()),
                ('punteggio', models.IntegerField()),
                ('immagine', models.ImageField(blank=True, upload_to='proposte/')),
            ],
        ),
    ]
