# Generated by Django 5.0.7 on 2024-07-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_subtitle_article_visible_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='visible_at',
            field=models.DateTimeField(),
        ),
    ]
