# Generated by Django 5.0.7 on 2024-07-29 07:13

import home.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_visible_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.ImageField(upload_to='images/', validators=[home.validator.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[home.validator.validate_image_size]),
        ),
    ]
