# Generated by Django 5.0.7 on 2024-10-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_section_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='articles',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
