# Generated by Django 5.0.7 on 2024-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
    ]
