# Generated by Django 5.0.7 on 2024-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiche', '0008_element_rank_delete_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
