# Generated by Django 5.0.7 on 2024-10-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiche', '0010_alter_category_description_alter_element_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
